### PR TITLE
WIP: Workflow updates

### PR DESCRIPTION
**Pull request by snmishra**

### CODE REVIEW

**Review by krister-ts — APPROVED** [review]
All looks good. Great work on these docs!

**Comment by krister-ts** [comment]
@snmishra Since you are modernizing. Maybe you want to look at using `pdm` instead of setuptools. I have used in a few small projects and it has been pretty easy to work with.

**Comment by snmishra** [comment]
It's a good idea to use something with more features. pdm, hatch, and I forget what else are looking interesting. I am waiting to see which way the packaging changes shake out. setuptools is a safe choice for now.

**Comment by krister-ts** [comment]
@snmishra I can't see your github page. I think for free tier you might need to set `snmishra.github.io` repo to public.

**Comment by krister-ts** [comment]
I tried out on my own:
image

**Comment by snmishra** [comment]
The page URL changed because of the org. I ran the docs workflow again.

**Pull request merged**
